### ISSUE TITLE
0.4.0 generates only the first page

### ISSUE THREAD

**Issue by albertosantini** [fortes/enfield#46]
Sigh.

I tested on Windows and on Linux.
It seems the generated pages are empty, but the first one, containing all the content of the other pages (the copy of the other assets is ok).

**Comment by zoitec** [comment]
I've also noticed this today on my mac installed via npm..

**Comment by albertosantini** [comment]
For a few hours I debugged the code.

It seems there is a glitch in `renderLiquidPostContent` (`generated.coffe`): the buffer is not cleared, but the content is accumulated: maybe the global `context` and the async nature of the building pipeline don't work well together.

Sadly I could not fix it.

**Comment by albertosantini** [comment]
Thanks for the ride, but the time is over. :)
See #45 for alternate solutions.
